version: '3.3'

services:
  rtl-433tomqtt:
    image: 'bademux/rtl_433tomqtt:latest'
    hostname: rtl-433tomqtt
    container_name: rtl-433tomqtt
    restart: unless-stopped
    volumes:
      - ./rtl_433.conf:/etc/rtl_433/rtl_433.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/bus/usb/001/002:/dev/bus/usb/001/002

networks:
  default:
    name: traefik_external
    external: true
