version: '3.3'

services:
  nodered:
    container_name: automation-nodered
    image: nodered/node-red
    restart: unless-stopped
    user: "0"
    privileged: true
    environment:
      - TZ=Europe/Berlin
    ports:
      - 1880:1880
    volumes:
      - nodered-data:/data

volumes:
  nodered-data:


networks:
  default:
    name: traefik_external
    external: true
