version: '3.3'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: automation-node-red
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
    name: node-red-data

networks:
  default:
    name: traefik_external
    external: true
